ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 40, in main
    welcome = oWel.WelcomeWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\module\winwelcome.py", line 55, in __init__
    if not self.initWindow(warn="mode"):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\module\winwelcome.py", line 95, in initWindow
    self.brwsloc.insert(0, self.localdata["datafolderloca"])
KeyError: 'datafolderloca'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 40, in main
    welcome = oWel.WelcomeWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowwelcome.py", line 41, in __init__
    super(WelcomeWindow, self).__init__("Welcome to OpenMark!", self.localconfig, self.repoconfig, menu=False)
AttributeError: 'WelcomeWindow' object has no attribute 'localconfig'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 40, in main
    welcome = oWel.WelcomeWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowwelcome.py", line 41, in __init__
    super(WelcomeWindow, self).__init__("Welcome to OpenMark!", self.localconfig, self.repoconfig, menu=False)
AttributeError: 'WelcomeWindow' object has no attribute 'localconfig'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 40, in main
    welcome = oWel.WelcomeWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowwelcome.py", line 63, in __init__
    if not self.initWindow(warn="datafolderloca"):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowwelcome.py", line 70, in initWindow
    self.window.resizable(0,0) #block resizing for the welcome window.
  File "C:\Python34\lib\tkinter\__init__.py", line 1798, in wm_resizable
    return self.tk.call('wm', 'resizable', self._w, width, height)
_tkinter.TclError: can't invoke "wm" command: application has been destroyed
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localdata, welcome.repoconfig)
AttributeError: 'WelcomeWindow' object has no attribute 'localdata'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowadmin.py", line 29, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindow.py", line 40, in _initWindow
    self.window.attributes('-zoomed', True)
  File "C:\Python34\lib\tkinter\__init__.py", line 1616, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: wrong # args: should be "wm attributes window ?-alpha ?double?? ?-transparentcolor ?color?? ?-disabled ?bool?? ?-fullscreen ?bool?? ?-toolwindow ?bool?? ?-topmost ?bool??"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowadmin.py", line 29, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindow.py", line 41, in _initWindow
    self._centreWindow(self.window)
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindow.py", line 54, in _centreWindow
    size(scx, scy)
TypeError: 'bool' object is not callable
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowadmin.py", line 29, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindow.py", line 41, in _initWindow
    self._centreWindow(self.window)
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindow.py", line 50, in _centreWindow
    menu_height = win.winfo_height() + (titlebar_height + frm_width)
NameError: name 'win' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindowadmin.py", line 29, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindow.py", line 41, in _initWindow
    self._positionWindow(self.window)
  File "C:\Users\Matthew Muresan\git\OpenMarkAdmin\app\openwindow.py", line 55, in _positionWindow
    size = (w-scx, h-scy-menu_height)
NameError: name 'menu_height' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 35, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 61, in _windowClose
    print(self.window.master())
TypeError: 'NoneType' object is not callable
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 61, in _windowClose
    print(self.window.master())
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 61, in _windowClose
    print(self.window.master())
TypeError: 'NoneType' object is not callable
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 61, in _windowClose
    self.window.master.quit()
AttributeError: 'NoneType' object has no attribute 'quit'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 61, in _windowClose
    self.window.master.quit()
AttributeError: 'NoneType' object has no attribute 'quit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 61, in _windowClose
    self.window.master.quit()
AttributeError: 'NoneType' object has no attribute 'quit'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 63, in _windowClose
    self.parentWindow.destroy()
AttributeError: 'MainWin' object has no attribute 'destroy'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in _windowClose
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 48, in _buildToolbar
    mainPane = tk.Frame(toolbarcontent, relief=tk.GROOVE, pdx=2, pady=2)
  File "C:\Python34\lib\tkinter\__init__.py", line 2582, in __init__
    Widget.__init__(self, master, 'frame', cnf, {}, extra)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-pdx"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self.window.pack(fill=tk.X)
  File "C:\Python34\lib\tkinter\__init__.py", line 1932, in __getattr__
    return getattr(self.tk, attr)
AttributeError: 'tkapp' object has no attribute 'pack'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 49, in _buildToolbar
    mainPane = ttk.Frame(toolbarcontent, relief=tk.SUNKEN, padx=2, pady=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 736, in __init__
    Widget.__init__(self, master, "ttk::frame", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-pady"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    bottomSep = ttk.Separator(window, orient=tk.VERTICAL)
NameError: name 'window' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 53, in _buildToolbar
    mainPane.grid(row=0, col=1, sticky=tk.LEFT)
  File "C:\Python34\lib\tkinter\__init__.py", line 2057, in grid_configure
    + self._options(cnf, kw))
_tkinter.TclError: ambiguous option "-col": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 53, in _buildToolbar
    mainPane.grid(row=0, col=0, sticky=tk.W)
  File "C:\Python34\lib\tkinter\__init__.py", line 2057, in grid_configure
    + self._options(cnf, kw))
_tkinter.TclError: ambiguous option "-col": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 53, in _buildToolbar
    mainPane.grid(row=0, col=0, sticky=tk.W)
  File "C:\Python34\lib\tkinter\__init__.py", line 2057, in grid_configure
    + self._options(cnf, kw))
_tkinter.TclError: ambiguous option "-col": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 53, in _buildToolbar
    mainPane.grid(row=0, col=0, sticky=(tk.W))
  File "C:\Python34\lib\tkinter\__init__.py", line 2057, in grid_configure
    + self._options(cnf, kw))
_tkinter.TclError: ambiguous option "-col": must be -column, -columnspan, -in, -ipadx, -ipady, -padx, -pady, -row, -rowspan, or -sticky
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    toolbarcontent.pack(fill=tk.X)
  File "C:\Python34\lib\tkinter\__init__.py", line 1974, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager pack inside . which already has slaves managed by grid
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 53, in _buildToolbar
    modeSep = ttk.Separator(modepane, orient=tk.VERTICAL)
NameError: name 'modepane' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 70, in _buildToolbar
    modeSep.pack(side=tk.RIGHT, fill=tk.Y)
  File "C:\Python34\lib\tkinter\__init__.py", line 1974, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager pack inside .45659888.45659920 which already has slaves managed by grid
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", borderwidth=2)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-borderwidth"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 86, in _buildToolbar
    peopleButton.state("pressed")
  File "C:\Python34\lib\tkinter\ttk.py", line 589, in state
    return self.tk.splitlist(str(self.tk.call(self._w, "state", statespec)))
_tkinter.TclError: Invalid state name p
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 85, in _buildToolbar
    peopleButton = ttk.Button(modePane, text="People", callback=self._windowClose)
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-callback"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 75, in _windowClose
    self._windowPreClose()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 105, in _windowPreClose
    print(peopleButton.state())
NameError: name 'peopleButton' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 75, in _windowClose
    self._windowPreClose()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 105, in _windowPreClose
    print(peopleButton.state())
NameError: name 'peopleButton' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 48, in _initWindow
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1537, in __call__
    self.widget._report_exception()
  File "C:\Python34\lib\tkinter\__init__.py", line 1286, in _report_exception
    root.report_callback_exception(exc, val, tb)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 86, in _callError
    errorHandle.callError(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 60, in callError
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    sys.exit()
SystemExit
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 86, in _buildToolbar
    peopleButton.state("active")
  File "C:\Python34\lib\tkinter\ttk.py", line 589, in state
    return self.tk.splitlist(str(self.tk.call(self._w, "state", statespec)))
_tkinter.TclError: Invalid state name a
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 86, in _buildToolbar
    peopleButton.state("pressed")
  File "C:\Python34\lib\tkinter\ttk.py", line 589, in state
    return self.tk.splitlist(str(self.tk.call(self._w, "state", statespec)))
_tkinter.TclError: Invalid state name p
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 86, in _buildToolbar
    peopleButton.state('pressed')
  File "C:\Python34\lib\tkinter\ttk.py", line 589, in state
    return self.tk.splitlist(str(self.tk.call(self._w, "state", statespec)))
_tkinter.TclError: Invalid state name p
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 86, in _buildToolbar
    peopleButton.state(['pressed']['disabled'])
TypeError: list indices must be integers, not str
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 39, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 83, in _buildToolbar
    saveimg = tk.PhotoImage(file="resources/icons/save.gif")
  File "C:\Python34\lib\tkinter\__init__.py", line 3416, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 3372, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "resources/icons/save.gif": no such file or directory
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 71, in _BuildMainWindow
    mainNotebook.pack(fill=tk.BOTH)
NameError: name 'mainNotebook' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 72, in _BuildMainWindow
    rightNotebook1.add(rightNotebook1, text="Basic")
AttributeError: 'Frame' object has no attribute 'add'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 77, in _BuildMainWindow
    leftNotebook.pack(row=0, column=1)
  File "C:\Python34\lib\tkinter\__init__.py", line 1974, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: bad option "-row": must be -after, -anchor, -before, -expand, -fill, -in, -ipadx, -ipady, -padx, -pady, or -side
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 61, in _BuildMainWindow
    leftNotebook1Listbox.insert(i, *testlist[i])
TypeError: list indices must be integers, not str
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 61, in _BuildMainWindow
    leftNotebook1Listbox.insert(testlist[i])
TypeError: list indices must be integers, not str
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 61, in _BuildMainWindow
    leftNotebook1Listbox.insert(testlist)
  File "C:\Python34\lib\tkinter\__init__.py", line 2644, in insert
    self.tk.call((self._w, 'insert', index) + elements)
_tkinter.TclError: bad listbox index "['Muresan, Matthew', 'Muresan, Tiffany']": must be active, anchor, end, @x,y, or a number
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 61, in _BuildMainWindow
    leftNotebook1Listbox.insert(END, i, *testlist[i])
NameError: name 'END' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 31, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 42, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 61, in _BuildMainWindow
    leftNotebook1Listbox.insert(tk.END, i, *testlist[i])
TypeError: list indices must be integers, not str
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 72, in _BuildMainWindow
    testlab = ttk.Label(basicInfo, text="test", relief=tk.GROOVE, background="#FFE6E6", width=20, height=1)
  File "C:\Python34\lib\tkinter\ttk.py", line 755, in __init__
    Widget.__init__(self, master, "ttk::label", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-height"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 80, in _BuildMainWindow
    testent.pack(row=0, column=1)
  File "C:\Python34\lib\tkinter\__init__.py", line 1974, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: bad option "-row": must be -after, -anchor, -before, -expand, -fill, -in, -ipadx, -ipady, -padx, -pady, or -side
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 82, in _BuildMainWindow
    testlab2.pack(row=0, column=3)
  File "C:\Python34\lib\tkinter\__init__.py", line 1974, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: bad option "-row": must be -after, -anchor, -before, -expand, -fill, -in, -ipadx, -ipady, -padx, -pady, or -side
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 86, in _BuildMainWindow
    basicInfo.colormodel(2, minsize=20)
TypeError: colormodel() got an unexpected keyword argument 'minsize'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 73, in _BuildMainWindow
    testlab = tk.Label(basicInfo, text="test", relief=tk.GROOVE, background="#FFE6E6", width=20, borderwidth=1, anchor=tk.RIGHT)
  File "C:\Python34\lib\tkinter\__init__.py", line 2604, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: bad anchor "right": must be n, ne, e, se, s, sw, w, nw, or center
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 74, in _BuildMainWindow
    testent = tk.Entry(basicInfo, relief=tk.GROOVE, background="#FFE6E6", activebackground="#FFF0F0", width=20, borderwidth=1)
  File "C:\Python34\lib\tkinter\__init__.py", line 2514, in __init__
    Widget.__init__(self, master, 'entry', cnf, kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-activebackground"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 114, in _buildToolbar
    saveimg = tk.PhotoImage(file="resources\icons\bitcons\icons\gif\tan\16x16")
  File "C:\Python34\lib\tkinter\__init__.py", line 3416, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 3372, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "resources\iconsitcons\icons\gif	anx16": no such file or directory
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 40, in _initWindow
    self._buildToolbar(toolbarcontent)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 114, in _buildToolbar
    saveimg = tk.PhotoImage(file="resources\icons\bitcons\icons\gif\tan\16x16\save.gif")
  File "C:\Python34\lib\tkinter\__init__.py", line 3416, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 3372, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "resources\iconsitcons\icons\gif	anx16\save.gif": no such file or directory
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 30, in __init__
    super(MainWin, self).__init__("OpenMarkAdmin", localconfig, repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 26, in __init__
    self._skelInit()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 46, in _skelInit
    self.helpMenu.add_command(label="About", command=self._showAbout())
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramWindow()
NameError: name 'AboutProgramWindow' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 30, in __init__
    super(MainWin, self).__init__("OpenMarkAdmin", localconfig, repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 26, in __init__
    self._skelInit()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 46, in _skelInit
    self.helpMenu.add_command(label="About", command=self._showAbout())
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialogabout.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialogabout.py", line 37, in _initWindow
    super(AboutProgramDialog, self).__init__("Welcome to OpenMark!", self.localconfig, self.repoconfig, menu=False)
AttributeError: 'AboutProgramDialog' object has no attribute 'localconfig'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 30, in __init__
    super(MainWin, self).__init__("OpenMarkAdmin", localconfig, repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 26, in __init__
    self._skelInit()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 46, in _skelInit
    self.helpMenu.add_command(label="About", command=self._showAbout())
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialogabout.py", line 34, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialogabout.py", line 37, in _initWindow
    super(AboutProgramDialog, self).__init__("About OpenMarkSheets")
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialog.py", line 35, in __init__
    self._skelInit()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialog.py", line 42, in _skelInit
    self.window = tk.Toplevel(self)
  File "C:\Python34\lib\tkinter\__init__.py", line 2165, in __init__
    BaseWidget.__init__(self, master, 'toplevel', cnf, {}, extra)
  File "C:\Python34\lib\tkinter\__init__.py", line 2115, in __init__
    BaseWidget._setup(self, master, cnf)
  File "C:\Python34\lib\tkinter\__init__.py", line 2093, in _setup
    self.tk = master.tk
AttributeError: 'AboutProgramDialog' object has no attribute 'tk'
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 30, in __init__
    super(MainWin, self).__init__("OpenMarkAdmin", localconfig, repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 26, in __init__
    self._skelInit()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 46, in _skelInit
    self.helpMenu.add_command(label="About", command=self._showAbout())
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
TypeError: __init__() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 49, in _initWindow
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1537, in __call__
    self.widget._report_exception()
  File "C:\Python34\lib\tkinter\__init__.py", line 1286, in _report_exception
    root.report_callback_exception(exc, val, tb)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 96, in _callError
    errorHandle.callError(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 60, in callError
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    sys.exit()
SystemExit
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
TypeError: __init__() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 49, in _initWindow
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1537, in __call__
    self.widget._report_exception()
  File "C:\Python34\lib\tkinter\__init__.py", line 1286, in _report_exception
    root.report_callback_exception(exc, val, tb)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 96, in _callError
    errorHandle.callError(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 60, in callError
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    sys.exit()
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
TypeError: __init__() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 49, in _initWindow
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1537, in __call__
    self.widget._report_exception()
  File "C:\Python34\lib\tkinter\__init__.py", line 1286, in _report_exception
    root.report_callback_exception(exc, val, tb)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 96, in _callError
    errorHandle.callError(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 60, in callError
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    sys.exit()
SystemExit
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 49, in _initWindow
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1537, in __call__
    self.widget._report_exception()
  File "C:\Python34\lib\tkinter\__init__.py", line 1286, in _report_exception
    root.report_callback_exception(exc, val, tb)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 97, in _callError
    errorHandle.callError(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 60, in callError
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    sys.exit()
SystemExit
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 49, in _initWindow
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1537, in __call__
    self.widget._report_exception()
  File "C:\Python34\lib\tkinter\__init__.py", line 1286, in _report_exception
    root.report_callback_exception(exc, val, tb)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 97, in _callError
    errorHandle.callError(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 60, in callError
    self.window.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    sys.exit(0)
SystemExit: 0
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    os._exit()
TypeError: _exit() takes exactly 1 argument (0 given)
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    os._exit()
TypeError: _exit() takes exactly 1 argument (0 given)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\module\errorsend.py", line 65, in _windowClose
    os._exit()
TypeError: _exit() takes exactly 1 argument (0 given)
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    raise
RuntimeError: No active exception to reraise
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindow.py", line 58, in _showAbout
    AboutProgramDialog(self.window)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialogabout.py", line 35, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\opendialogabout.py", line 62, in _initWindow
    ok = ttk.Button(buttonscontent, text="Okay", command=self._windowClose())
  File "C:\Python34\lib\tkinter\ttk.py", line 608, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "C:\Python34\lib\tkinter\ttk.py", line 553, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python34\lib\tkinter\__init__.py", line 2122, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: bad window path name ".45698448.45698576.45752464"
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 51, in _BuildMainWindow
    leftNoteFrame = ttkFrame(mainwindow)
NameError: name 'ttkFrame' is not defined
ERROR:root:An Exception Occurred
Traceback (most recent call last):
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\main.py", line 44, in main
    mainWin = oAdmin.MainWin(welcome.localconfig, welcome.repoconfig)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 32, in __init__
    self._initWindow()
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 43, in _initWindow
    self._BuildMainWindow(mainwindow)
  File "C:\Users\Matthew Muresan\git\OpenMarkSheets\app\openwindowadmin.py", line 105, in _BuildMainWindow
    searchEnt.pack(side=tk.X, expand=1)
  File "C:\Python34\lib\tkinter\__init__.py", line 1974, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: bad side "x": must be top, bottom, left, or right
